// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Uid      string `json:"uid"`
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	AvatarId uint32 `json:"avatar_id"`
	Elo      int32  `json:"elo"`
	Tier     string `json:"tier"`
	Gold     int32  `json:"gold"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
}

type RegisterResp struct {
	Uid   string `json:"uid"`
	Token string `json:"token"`
}

type UserInfoResp struct {
	Uid      string `json:"uid"`
	Nickname string `json:"nickname"`
	AvatarId uint32 `json:"avatar_id"`
	Elo      int32  `json:"elo"`
	Tier     string `json:"tier"`
	Gold     int32  `json:"gold"`
	Wins     int32  `json:"wins"`
	Losses   int32  `json:"losses"`
}
